services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vivid-valid-backend-prod
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3001}
      - FRONTEND_URL=${FRONTEND_URL:-https://yourdomain.com}
      - BACKEND_URL=${BACKEND_URL:-https://api.yourdomain.com}
      - LOG_LEVEL=info

      # Rate Limiting (stricter for production)
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-50}
      - SINGLE_EMAIL_RATE_WINDOW_MS=${SINGLE_EMAIL_RATE_WINDOW_MS:-60000}
      - SINGLE_EMAIL_RATE_MAX=${SINGLE_EMAIL_RATE_MAX:-10}
      - BULK_EMAIL_RATE_WINDOW_MS=${BULK_EMAIL_RATE_WINDOW_MS:-300000}
      - BULK_EMAIL_RATE_MAX=${BULK_EMAIL_RATE_MAX:-2}

      # SMTP Configuration
      - SMTP_TIMEOUT=${SMTP_TIMEOUT:-5000}
      - SMTP_FROM_DOMAIN=${SMTP_FROM_DOMAIN:-validator.yourdomain.com}
      - SMTP_PORT=${SMTP_PORT:-25}
      - SMTP_SECURE=${SMTP_SECURE:-false}

      # Cache Configuration (longer TTL for production)
      - DNS_CACHE_TTL=${DNS_CACHE_TTL:-600}
      - DISPOSABLE_CACHE_TTL=${DISPOSABLE_CACHE_TTL:-86400}
      - TYPO_CORRECTION_CACHE_TTL=${TYPO_CORRECTION_CACHE_TTL:-7200}
      - BULK_CACHE_TTL=${BULK_CACHE_TTL:-3600}

      # Validation Configuration
      - MAX_EMAIL_LENGTH=${MAX_EMAIL_LENGTH:-320}
      - MAX_LOCAL_PART_LENGTH=${MAX_LOCAL_PART_LENGTH:-64}
      - MAX_DOMAIN_LENGTH=${MAX_DOMAIN_LENGTH:-253}
      - MAX_DOMAIN_LABEL_LENGTH=${MAX_DOMAIN_LABEL_LENGTH:-63}
      - MIN_TLD_LENGTH=${MIN_TLD_LENGTH:-2}
      - MAX_TLD_LENGTH=${MAX_TLD_LENGTH:-6}

      # Bulk Validation Configuration
      - MAX_CONCURRENCY=${MAX_CONCURRENCY:-5}
      - BATCH_SIZE=${BATCH_SIZE:-20}
      - BATCH_DELAY_MS=${BATCH_DELAY_MS:-200}
      - MAX_BULK_EMAILS=${MAX_BULK_EMAILS:-500}

      # Scoring Configuration
      - BASE_SCORE=${BASE_SCORE:-50}
      - SYNTAX_WEIGHT=${SYNTAX_WEIGHT:-25}
      - DOMAIN_WEIGHT=${DOMAIN_WEIGHT:-20}
      - MX_WEIGHT=${MX_WEIGHT:-25}
      - SMTP_WEIGHT=${SMTP_WEIGHT:-20}
      - DOMAIN_HEALTH_WEIGHT=${DOMAIN_HEALTH_WEIGHT:-15}

      # Strict Mode Thresholds
      - STRICT_MODE_SCORE_THRESHOLD=${STRICT_MODE_SCORE_THRESHOLD:-90}
      - STRICT_MODE_RISKY_THRESHOLD=${STRICT_MODE_RISKY_THRESHOLD:-70}
      - NORMAL_MODE_SCORE_THRESHOLD=${NORMAL_MODE_SCORE_THRESHOLD:-85}
      - NORMAL_MODE_RISKY_THRESHOLD=${NORMAL_MODE_RISKY_THRESHOLD:-65}

      # Penalty Configuration
      - DISPOSABLE_PENALTY=${DISPOSABLE_PENALTY:-40}
      - DISPOSABLE_PENALTY_STRICT=${DISPOSABLE_PENALTY_STRICT:-50}
      - BLACKLISTED_PENALTY=${BLACKLISTED_PENALTY:-50}
      - BLACKLISTED_PENALTY_STRICT=${BLACKLISTED_PENALTY_STRICT:-60}
      - ROLE_BASED_PENALTY=${ROLE_BASED_PENALTY:-15}
      - ROLE_BASED_PENALTY_STRICT=${ROLE_BASED_PENALTY_STRICT:-25}
      - FREE_PROVIDER_PENALTY=${FREE_PROVIDER_PENALTY:-5}
      - FREE_PROVIDER_PENALTY_STRICT=${FREE_PROVIDER_PENALTY_STRICT:-10}
      - TYPO_PENALTY=${TYPO_PENALTY:-15}
      - TYPO_PENALTY_STRICT=${TYPO_PENALTY_STRICT:-25}

      # Health Check Configuration
      - HEALTH_CHECK_INTERVAL_MS=${HEALTH_CHECK_INTERVAL_MS:-30000}
      - HEALTH_CHECK_TIMEOUT_MS=${HEALTH_CHECK_TIMEOUT_MS:-10000}
      - HEALTH_CHECK_START_PERIOD_MS=${HEALTH_CHECK_START_PERIOD_MS:-40000}
      - HEALTH_CHECK_RETRIES=${HEALTH_CHECK_RETRIES:-3}

      # CORS Configuration
      - CORS_ORIGIN=${CORS_ORIGIN:-https://yourdomain.com}
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    volumes:
      - ./backend/src/data:/app/src/data:ro
    networks:
      - vivid-valid-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:${PORT:-3001}/health",
        ]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: ${HEALTH_CHECK_RETRIES:-3}
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vivid-valid-frontend-prod
    restart: always
    environment:
      - VITE_API_BASE_URL=http://backend:3001/api
      - VITE_APP_NAME=${VITE_APP_NAME:-Email Verifier Pro}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
      - VITE_APP_DESCRIPTION=${VITE_APP_DESCRIPTION:-The most advanced email verification tool with real-time validation}
      - VITE_MAX_FILE_SIZE=${VITE_MAX_FILE_SIZE:-10485760}
      - VITE_SUPPORTED_FILE_TYPES=${VITE_SUPPORTED_FILE_TYPES:-.csv,.txt}
      - VITE_MAX_BULK_EMAILS=${VITE_MAX_BULK_EMAILS:-500}
      - FRONTEND_PORT=${FRONTEND_PORT:-8080}
    ports:
      - "${FRONTEND_PORT:-8080}:${FRONTEND_PORT:-8080}"
    depends_on:
      - backend
    networks:
      - vivid-valid-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:${FRONTEND_PORT:-8080}",
        ]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M

# Networks
networks:
  vivid-valid-network:
    driver: bridge

# Volumes
volumes:
  backend-data:
    driver: local
