# Nixpacks configuration for Vivid Valid Email Validator
[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-8_x"]

[phases.install]
cmds = [
    "npm install -g pnpm"
]

[phases.build]
cmds = [
    "pnpm install",
    "npm run build",
    "cd backend && pnpm install"
]

[start]
cmd = "sh -c 'cd backend && PORT=3001 npm start & npx serve -s dist -l 8080'"

[env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[[services]]
internalPort = 3001
protocol = "tcp"

[[services]]
internalPort = 8080
protocol = "tcp"